[libraries]
lib.files=[
	"*/*.vhdl"
]
lib.exclude = [
	"*/test*"
]

fsm.files = [
	"state_machine/*.vhdl"
]
counter.files = [
	"counter/*.vhdl"
]

sev_seg.files = [
	"seven_segment/*.vhdl"
]

reg.files = [
	"register/*.vhdl"
]

timer.files = [
	"timer/*.vhdl",
	"state_machine/*.vhdl"
]

main.file = [
	"*.vhdl",
	"state_machine/*.vhdl",
	"seven_segment/*.vhdl"
]

